Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using CaldwellHotels.Models;

namespace CaldwellHotels.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }
        public IActionResult Admin()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Controllers/PeopleController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using CaldwellHotels.Data;
using CaldwellHotels.Models;
using Microsoft.AspNetCore.Authorization;

namespace CaldwellHotels.Controllers
{
    [Authorize (Roles ="Administrator,Employee")]
    public class PeopleController : Controller
    {
        private readonly ApplicationDbContext _context;

        public PeopleController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: People
        [AllowAnonymous]
        public async Task<IActionResult> Index()
        {
            return View(await _context.Persons.ToListAsync());
        }

        // GET: People/Details/5
        [AllowAnonymous]
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var person = await _context.Persons
                .FirstOrDefaultAsync(m => m.PersonID == id);
            if (person == null)
            {
                return NotFound();
            }

            return View(person);
        }

        // GET: People/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: People/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("PersonID,FirstName,LastName,PhoneNumber,EmailAddress,StreetAddress,City,Province,Country,PostalCode")] Person person)
        {
            if (ModelState.IsValid)
            {
                _context.Add(person);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(person);
        }

        // GET: People/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var person = await _context.Persons.FindAsync(id);
            if (person == null)
            {
                return NotFound();
            }
            return View(person);
        }

        // POST: People/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("PersonID,FirstName,LastName,PhoneNumber,EmailAddress,StreetAddress,City,Province,Country,PostalCode")] Person person)
        {
            if (id != person.PersonID)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(person);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!PersonExists(person.PersonID))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(person);
        }

        // GET: People/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var person = await _context.Persons
                .FirstOrDefaultAsync(m => m.PersonID == id);
            if (person == null)
            {
                return NotFound();
            }

            return View(person);
        }

        // POST: People/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var person = await _context.Persons.FindAsync(id);
            _context.Persons.Remove(person);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool PersonExists(int id)
        {
            return _context.Persons.Any(e => e.PersonID == id);
        }
    }
}

Controllers/RoomStylesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using CaldwellHotels.Data;
using CaldwellHotels.Models;
using Microsoft.AspNetCore.Authorization;

namespace CaldwellHotels.Controllers
{
    [Authorize(Roles = "Administrator")]
    public class RoomStylesController : Controller
    {
        private readonly ApplicationDbContext _context;

        public RoomStylesController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: RoomStyles
        [AllowAnonymous]
        public async Task<IActionResult> Index()
        {
            return View(await _context.RoomStyles.ToListAsync());
        }

        // GET: RoomStyles/Details/5
        [AllowAnonymous]
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var roomStyle = await _context.RoomStyles
                .FirstOrDefaultAsync(m => m.StyleID == id);
            if (roomStyle == null)
            {
                return NotFound();
            }

            return View(roomStyle);
        }

        // GET: RoomStyles/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: RoomStyles/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        
        public async Task<IActionResult> Create([Bind("StyleID,BedroomDescription,BathroomDescription,KitchenDescription")] RoomStyle roomStyle)
        {
            if (ModelState.IsValid)
            {
                _context.Add(roomStyle);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(roomStyle);
        }

        // GET: RoomStyles/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var roomStyle = await _context.RoomStyles.FindAsync(id);
            if (roomStyle == null)
            {
                return NotFound();
            }
            return View(roomStyle);
        }

        // POST: RoomStyles/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("StyleID,BedroomDescription,BathroomDescription,KitchenDescription")] RoomStyle roomStyle)
        {
            if (id != roomStyle.StyleID)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(roomStyle);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!RoomStyleExists(roomStyle.StyleID))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(roomStyle);
        }

        // GET: RoomStyles/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var roomStyle = await _context.RoomStyles
                .FirstOrDefaultAsync(m => m.StyleID == id);
            if (roomStyle == null)
            {
                return NotFound();
            }

            return View(roomStyle);
        }

        // POST: RoomStyles/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var roomStyle = await _context.RoomStyles.FindAsync(id);
            _context.RoomStyles.Remove(roomStyle);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool RoomStyleExists(int id)
        {
            return _context.RoomStyles.Any(e => e.StyleID == id);
        }
    }
}

Controllers/RoomsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using CaldwellHotels.Data;
using CaldwellHotels.Models;
using Microsoft.AspNetCore.Authorization;

namespace CaldwellHotels.Controllers
{
    [Authorize(Roles = "Administrator")]
    public class RoomsController : Controller
    {
        private readonly ApplicationDbContext _context;

        public RoomsController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: Rooms
        [AllowAnonymous]
        public async Task<IActionResult> Index()
        {
            var applicationDbContext = _context.Rooms.Include(r => r.RoomStyle);
            return View(await applicationDbContext.ToListAsync());
        }

        // GET: Rooms/Details/5
        [AllowAnonymous]
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var room = await _context.Rooms
                .Include(r => r.RoomStyle)
                .FirstOrDefaultAsync(m => m.RoomID == id);
            if (room == null)
            {
                return NotFound();
            }

            return View(room);
        }

        // GET: Rooms/Create
        public IActionResult Create()
        {
            ViewData["StyleID"] = new SelectList(_context.RoomStyles, "StyleID", "StyleID");
            return View();
        }

        // POST: Rooms/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("RoomID,RoomFloor,RoomAccessible,StyleID")] Room room)
        {
            if (ModelState.IsValid)
            {
                _context.Add(room);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["StyleID"] = new SelectList(_context.RoomStyles, "StyleID", "StyleID", room.StyleID);
            return View(room);
        }

        // GET: Rooms/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var room = await _context.Rooms.FindAsync(id);
            if (room == null)
            {
                return NotFound();
            }
            ViewData["StyleID"] = new SelectList(_context.RoomStyles, "StyleID", "StyleID", room.StyleID);
            return View(room);
        }

        // POST: Rooms/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("RoomID,RoomFloor,RoomAccessible,StyleID")] Room room)
        {
            if (id != room.RoomID)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(room);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!RoomExists(room.RoomID))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["StyleID"] = new SelectList(_context.RoomStyles, "StyleID", "StyleID", room.StyleID);
            return View(room);
        }

        // GET: Rooms/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var room = await _context.Rooms
                .Include(r => r.RoomStyle)
                .FirstOrDefaultAsync(m => m.RoomID == id);
            if (room == null)
            {
                return NotFound();
            }

            return View(room);
        }

        // POST: Rooms/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var room = await _context.Rooms.FindAsync(id);
            _context.Rooms.Remove(room);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool RoomExists(int id)
        {
            return _context.Rooms.Any(e => e.RoomID == id);
        }
    }
}

Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-1 list-group-item bg-light font-weight-bold">Caldwell Hotels</h1>
    <div class="d-flex flex-row">
        <div class="p-4 text-left">
            <p style="text-indent:30px">
                Welcome to Caldwell Hotels - I've heard your interested in our website and how we operate so lets get to it.
                Our website is running on the fastest localdb I can find, it features 4 unique tables as listed
            </p>
            <ul>
                <li>Persons Table - Responsible for knowing all about you, it contains a variety of contact information based strings and a primary key  </li>
                <li>RoomStyles Table - Feauturing a numbered list that describes each room variant based on its accomadations</li>
                <li>Rooms Table - Contains generic room information such as whether the room is easily accessible, what floor its on, and links to the RoomStyles table</li>
                <li>Reservation Table - Here is where all the data comes together, by linking People to Rooms, and then linking that to a start and end date, we create an effective record that determines what rooms are avaialble and when. </li>

            </ul>
        </div>
        <div class="p-4">
        </div>
        <div class="p-4">
            <!--//Image courtesy of https://www.shutterstock.com/image-photo/young-chef-couple-cooking-modern-restaurant-1690531333, Retrieved on 2020/10/22 -->
            <img src="https://image.shutterstock.com/image-photo/young-chef-couple-cooking-modern-600w-1690531333.jpg" alt="Chefs in a pristine environment" />
        </div>

    </div>
    <div class="d-flex flex-row">
        <div class="p-2">
            <!-- //Image courtesy of https://www.shutterstock.com/image-photo/real-estate-luxury-interior-exterior-design-660324757, Retrieved on 2020/10/22 -->
            <img src="https://image.shutterstock.com/image-photo/real-estate-luxury-interior-exterior-600w-660324757.jpg" alt="Wooden patio by pool" />
        </div>
        <div class="p-2 text-left">
            <p style="text-indent:30px">
                In addition to our beautifully hand-crafted database, we've got a modular .html
                setup based in ASP.NET using the MVC architecture. Unfortunately, many of these files are autogenerated
                and aren't worth exploring in detail. The most notable files are as follows:
            </p>
            <ul>
                <li>admin.cshtml - This is our admin panel, responsible for navigating our users to full CRUD functionality for each of our tables  </li>
                <li>ApplicationDBContext.cs - This is what allows our MySql database and Website to effectively communicate. An unhealthy amount of time was spent putting it together. </li>
                <li>The Models Folder - Contains the constructors for our various objects</li>
                <li>Note: The various files in the Models folder and ApplicationDBContext.cs are what I was responsible for migrating to form the effective communication mentioned earlier.</li>
            </ul>
        </div>

            </div>
        </div>

Views/Home/admin.cshtml
@{
    ViewData["Title"] = "Adminstration Panel";
}
<div class="text-center">
    <h4>Welcome to the admin panel, follow any of the links to their respecitive database management tools.</h4>


    <ul class="list-group-item text-primary bg-dark">
        <li class="list-group-item">
            <a class="nav-link text-center" asp-area="" asp-controller="Reservations" asp-action="Index">Reservations Explorer</a>
        </li>
        <li class="list-group-item bg-light">
            <a class="nav-link text-center" asp-area="" asp-controller="People" asp-action="Index">People Explorer</a>
        </li>
        <li class="list-group-item">
            <a class="nav-link text-center" asp-area="" asp-controller="Rooms" asp-action="Index">Rooms Explorer</a>
        </li>
        <li class="list-group-item bg-light">
            <a class="nav-link text-center" asp-area="" asp-controller="RoomStyles" asp-action="Index">Room Styles Explorer</a>
        </li>
    </ul>
</div>